### ISSUE TITLE
PR 65 has had some interesting side-effects

### ISSUE THREAD

**Issue by i-like-robots** [cloudchen/grunt-template-jasmine-requirejs#74]
This may not be a bug report as such but an interesting issue.

The changes made in https://github.com/cloudchen/grunt-template-jasmine-requirejs/pull/65 may introduce a new issue for users using jQuery or other libraries.

At Lonely Planet we use the nice [Jasmine jQuery](https://github.com/velesin/jasmine-jquery) utility to load fixtures, spy on events etc.

Jasmine jQuery is _not_ AMD compatible so we simply load it in as a helper script. This is also requires that we load jQuery onto the page first, done with the `vendor` option for the main Jasmine Grunt task.

Because RequireJS is now being loaded _after_ the vendor and helper scripts jQuery is not registering itself as an AMD module. This means our AMD specs are loading in a _new_ version of jQuery which introduces some interesting bugs.

As the two versions of jQuery are not the same internal data set by one instance is not shared with the other. For instance, event handlers are stored internally against an element. Jasmine jQuery features a useful `spyOnEvent` function which binds a simple handler, however because this is bound by the first version of jQuery loaded onto the page it is not triggered when the specs are run because they're dispatching events using a different jQuery instance.

I'm not sure what the best solution to this problem is but it's quite insidious to debug!

**Comment by cloudchen** [comment]
Will fix it by [compromise](https://github.com/cloudchen/grunt-template-jasmine-requirejs/pull/65#issuecomment-78216862). Thanks for sharing your thoughts.
