### ISSUE TITLE
src/templates/jasmine-requirejs.html styles needs to support less

### ISSUE THREAD

**Issue by joeheyming** [cloudchen/grunt-template-jasmine-requirejs#79]
The template needs to detect if the input is css or less.  If it is less, you need to output <link rel="stylesheet/less" >

  <% css.forEach(function(style){ %>
   <% if (style.match(/.less$/)) {>
  <link rel="stylesheet/less" type="text/css" href="<%= style %>">
  <% } else { %>
  <link rel="stylesheet" type="text/css" href="<%= style %>">
  <% }}) %>

**Comment by cloudchen** [comment]
Pre-process less files in other grunt tasks. This task only focuses on its own mission.

**Comment by joeheyming** [comment]
yeah i figured out a workaround elsewhere, thanks for your time!
